---
- name: Professional System Monitoring Suite
  hosts: localhost
  gather_facts: yes

  vars:
    cpu_threshold: 80
    ram_threshold: 80
    disk_threshold: 80

    telegram_bot_token: "YOUR_BOT_TOKEN"
    telegram_chat_id: "YOUR_CHAT_ID"

  tasks:

    - name: Ensure reports directory exists
      file:
        path: reports
        state: directory

    # ---------------------------
    # CPU USAGE
    # ---------------------------
    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print $2 + $4}'"
      register: cpu_usage_raw

    - name: Convert CPU usage
      set_fact:
        cpu_usage: "{{ cpu_usage_raw.stdout | float | round(0) | int }}"

    # ---------------------------
    # RAM USAGE
    # ---------------------------
    - name: Calculate RAM usage
      set_fact:
        ram_usage_percent: "{{ ((ansible_facts.memtotal_mb - ansible_facts.memfree_mb) / ansible_facts.memtotal_mb * 100) | float | round(0) | int }}"

    # ---------------------------
    # DISK USAGE
    # ---------------------------
    - name: Get disk usage
      shell: "df -h / | awk 'NR==2 {print $5}' | sed 's/%//'"
      register: disk_usage_raw

    - name: Convert disk usage
      set_fact:
        disk_usage: "{{ disk_usage_raw.stdout | int }}"

    # ---------------------------
    # SERVICES (WSL Compatible)
    # ---------------------------
    - name: Check SSH running (WSL-safe)
      shell: "pgrep ssh || true"
      register: ssh_status

    - name: Check cron running (WSL-safe)
      shell: "pgrep cron || pgrep crond || true"
      register: cron_status

    # ---------------------------
    # TXT REPORT
    # ---------------------------
    - name: Create system report (TXT)
      copy:
        dest: "reports/system_report.txt"
        content: |
          ===== SYSTEM REPORT =====
          CPU: {{ cpu_usage }}%
          RAM: {{ ram_usage_percent }}%
          DISK: {{ disk_usage }}%
          SSH running: {{ 'YES' if ssh_status.stdout != '' else 'NO' }}
          Cron running: {{ 'YES' if cron_status.stdout != '' else 'NO' }}
          ==========================

    # ---------------------------
    # HTML REPORT
    # ---------------------------
    - name: Create HTML report
      copy:
        dest: "reports/system_report.html"
        content: |
          <html>
          <head><title>System Monitoring</title></head>
          <body>
            <h1>System Monitoring Dashboard</h1>
            <h2>CPU: {{ cpu_usage }}%</h2>
            <h2>RAM: {{ ram_usage_percent }}%</h2>
            <h2>Disk: {{ disk_usage }}%</h2>
            <h3>SSH Running: {{ 'YES' if ssh_status.stdout != '' else 'NO' }}</h3>
            <h3>Cron Running: {{ 'YES' if cron_status.stdout != '' else 'NO' }}</h3>
          </body>
          </html>

    # ---------------------------
    # JSON METRICS
    # ---------------------------
    - name: Save metrics to JSON
      copy:
        dest: "reports/metrics.json"
        content: |
          {
            "cpu_usage": {{ cpu_usage | int }},
            "ram_usage_percent": {{ ram_usage_percent | int }},
            "disk_usage": {{ disk_usage | int }},
            "ssh_running": "{{ 'YES' if ssh_status.stdout != '' else 'NO' }}",
            "cron_running": "{{ 'YES' if cron_status.stdout != '' else 'NO' }}"
          }

    # ---------------------------
    # TELEGRAM ALERT
    # ---------------------------
    - name: Telegram alert if thresholds exceeded
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            🚨 SYSTEM ALERT 🚨
            CPU: {{ cpu_usage }}%
            RAM: {{ ram_usage_percent }}%
            DISK: {{ disk_usage }}%
        status_code: 200
      when: >
        cpu_usage | int > cpu_threshold or
        ram_usage_percent | int > ram_threshold or
        disk_usage | int > disk_threshold
